name: Deploy Azure SQL Database schema

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  
  deploy_database_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: windows-latest
    name: Deploy Database Job
    steps:
      - uses: actions/checkout@v1
      - uses: Azure/sql-action@v1
        with:
          server-name: bus-server976042.database.windows.net
          connection-string: Server=tcp:bus-server976042.database.windows.net,1433;Initial Catalog=bus-db;Persist Security Info=False;User ID=cloudadmin;Password=Letmein@1;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
          # uses dacpac to deploy database schema
          dacpac-package: './Database/dacpac/bus-db.dacpac'